'use client'

import Link from 'next/link'
import { useState } from 'react'
import { useQuery } from 'convex/react'
import { api } from '@/convex/_generated/api'
import { ArrowLeft, Search, ShieldCheck } from 'lucide-react'

const labels: Record<string, string> = { SUBMITTED: 'Submitted', UNDER_REVIEW: 'Under review', VERIFIED: 'Verified', ASSIGNED: 'Assigned', IN_PROGRESS: 'In progress', RESOLVED: 'Resolved', COMMUNITY_VERIFICATION: 'Community verification', VERIFIED_RESOLUTION: 'Verified resolution', REJECTED: 'Rejected', REOPENED: 'Reopened' }
const formatDate = (value: number) => new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short' }).format(value)

export default function TrackPage() {
  const [reference, setReference] = useState('')
  const [submitted, setSubmitted] = useState('')
  const issue = useQuery(api.issues.byReference, submitted ? { referenceNumber: submitted } : 'skip')
  return <main className="min-h-screen bg-[#f6f8fb] p-6 text-slate-900 sm:p-10"><div className="mx-auto max-w-2xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-[#245582]"><ArrowLeft size={16} /> Dashboard</Link><div className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start gap-4"><div className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#eaf1f8] text-[#245582]"><ShieldCheck size={23} /></div><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#4d83b1]">Public tracking</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Track a CivicFix report</h1><p className="mt-2 text-sm text-slate-500">Enter a reference number to see safe public status information.</p></div></div><form className="mt-7 flex gap-2" onSubmit={(event) => { event.preventDefault(); setSubmitted(reference.trim().toUpperCase()) }}><label htmlFor="reference" className="sr-only">Reference number</label><input id="reference" value={reference} onChange={(event) => setReference(event.target.value)} placeholder="CFX-2026-123456-01" className="h-11 min-w-0 flex-1 rounded-xl border border-slate-200 px-4 text-sm outline-none focus:border-[#7fa9cb] focus:ring-2 focus:ring-[#dbe9f6]" /><button className="inline-flex items-center gap-2 rounded-xl bg-[#163b66] px-4 text-xs font-semibold text-white" type="submit"><Search size={15} /> Track</button></form>{submitted && issue === undefined && <p className="mt-5 text-sm text-slate-500">Looking up {submitted}…</p>}{submitted && issue === null && <p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-800">No public report was found for that reference number.</p>}{issue && <div className="mt-6 rounded-2xl border border-slate-100 bg-slate-50 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold text-slate-400">{issue.referenceNumber}</p><h2 className="mt-1 text-lg font-bold">{issue.title}</h2></div><span className="rounded-full bg-white px-3 py-1.5 text-xs font-semibold text-[#245582]">{labels[issue.status] ?? issue.status}</span></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-xs text-slate-400">Category</dt><dd className="mt-1 font-medium">{issue.categoryName}</dd></div><div><dt className="text-xs text-slate-400">Submitted</dt><dd className="mt-1 font-medium">{formatDate(issue.createdAt)}</dd></div><div><dt className="text-xs text-slate-400">Last status update</dt><dd className="mt-1 font-medium">{formatDate(issue.lastStatusUpdate)}</dd></div><div><dt className="text-xs text-slate-400">Location</dt><dd className="mt-1 font-medium">{issue.address || 'Not provided'}</dd></div></dl></div>}</div></div></main>
}
