import { defineSchema, defineTable } from "convex/server"
import { authTables } from "@convex-dev/auth/server"
import { v } from "convex/values"

const role = v.union(v.literal("citizen"), v.literal("department_staff"), v.literal("department_admin"), v.literal("super_admin"))
const issueStatus = v.union(v.literal("SUBMITTED"), v.literal("UNDER_REVIEW"), v.literal("VERIFIED"), v.literal("ASSIGNED"), v.literal("IN_PROGRESS"), v.literal("RESOLVED"), v.literal("COMMUNITY_VERIFICATION"), v.literal("VERIFIED_RESOLUTION"), v.literal("REJECTED"), v.literal("REOPENED"))
const priority = v.union(v.literal("LOW"), v.literal("MEDIUM"), v.literal("HIGH"), v.literal("CRITICAL"))

export default defineSchema({
  ...authTables,
  profiles: defineTable({ authIdentityId: v.string(), name: v.string(), email: v.string(), role, departmentId: v.optional(v.id("departments")), isActive: v.boolean(), reputationPoints: v.number(), createdAt: v.number(), updatedAt: v.number() }).index("by_auth_identity", ["authIdentityId"]).index("by_role", ["role"]).index("by_department", ["departmentId"]),
  departments: defineTable({ name: v.string(), code: v.string(), description: v.optional(v.string()), isActive: v.boolean(), createdAt: v.number(), updatedAt: v.number() }).index("by_code", ["code"]),
  categories: defineTable({ name: v.string(), description: v.optional(v.string()), departmentId: v.id("departments"), defaultPriority: priority, defaultSlaHours: v.number(), isActive: v.boolean(), createdAt: v.number(), updatedAt: v.number() }).index("by_department", ["departmentId"]),
  issues: defineTable({ referenceNumber: v.string(), title: v.string(), description: v.string(), categoryId: v.id("categories"), departmentId: v.id("departments"), reporterId: v.id("profiles"), assigneeId: v.optional(v.id("profiles")), status: issueStatus, priority, priorityScore: v.number(), priorityReason: v.optional(v.string()), priorityCalculatedAt: v.optional(v.number()), aiAnalysis: v.optional(v.object({ suggestedCategory: v.string(), severity: v.string(), summary: v.string(), keywords: v.array(v.string()), suggestedDepartment: v.string(), safetyConcern: v.boolean(), priorityFactors: v.array(v.string()), analyzedAt: v.number() })), latitude: v.number(), longitude: v.number(), address: v.string(), landmark: v.optional(v.string()), city: v.string(), supportCount: v.number(), commentCount: v.number(), viewCount: v.number(), isPublic: v.boolean(), isDuplicate: v.boolean(), duplicateOf: v.optional(v.id("issues")), createdAt: v.number(), updatedAt: v.number(), resolvedAt: v.optional(v.number()), dueAt: v.optional(v.number()) }).index("by_reference", ["referenceNumber"]).index("by_reporter", ["reporterId"]).index("by_status", ["status"]).index("by_department", ["departmentId"]).index("by_assignee", ["assigneeId"]).index("by_created", ["createdAt"]),
  assignmentHistory: defineTable({ issueId: v.id("issues"), assigneeId: v.optional(v.id("profiles")), changedBy: v.id("profiles"), createdAt: v.number(), note: v.optional(v.string()) }).index("by_issue", ["issueId"]),
  resolutionEvidence: defineTable({ issueId: v.id("issues"), storageId: v.id("_storage"), uploadedBy: v.id("profiles"), description: v.string(), createdAt: v.number() }).index("by_issue", ["issueId"]),
  resolutionVerifications: defineTable({ issueId: v.id("issues"), userId: v.id("profiles"), accepted: v.boolean(), comment: v.optional(v.string()), createdAt: v.number() }).index("by_issue", ["issueId"]).index("by_user_issue", ["userId", "issueId"]),
  abuseReports: defineTable({ issueId: v.optional(v.id("issues")), reporterId: v.id("profiles"), reason: v.string(), createdAt: v.number(), status: v.union(v.literal("OPEN"), v.literal("REVIEWED")), reviewedBy: v.optional(v.id("profiles")), reviewedAt: v.optional(v.number()), reviewNote: v.optional(v.string()) }).index("by_status", ["status"]),
moderationActions: defineTable({ reportId: v.id("abuseReports"), moderatorId: v.id("profiles"), action: v.union(v.literal("DISMISS"), v.literal("HIDE_ISSUE"), v.literal("REOPEN_REPORT")), note: v.optional(v.string()), createdAt: v.number() }).index("by_report", ["reportId"]),
rateLimits: defineTable({ key: v.string(), windowStartedAt: v.number(), count: v.number() }).index("by_key", ["key"]),
  issueStatusHistory: defineTable({ issueId: v.id("issues"), previousStatus: v.optional(issueStatus), newStatus: issueStatus, changedBy: v.id("profiles"), timestamp: v.number(), note: v.optional(v.string()), metadata: v.optional(v.string()) }).index("by_issue", ["issueId"]),
  auditLogs: defineTable({ actorId: v.id("profiles"), action: v.string(), entityType: v.string(), entityId: v.string(), timestamp: v.number(), metadata: v.optional(v.string()) }).index("by_entity", ["entityType", "entityId"]),
  evidence: defineTable({ issueId: v.id("issues"), storageId: v.id("_storage"), uploaderId: v.id("profiles"), filename: v.string(), contentType: v.string(), createdAt: v.number() }).index("by_issue", ["issueId"]),
  comments: defineTable({ issueId: v.id("issues"), authorId: v.id("profiles"), body: v.string(), createdAt: v.number(), updatedAt: v.optional(v.number()) }).index("by_issue", ["issueId"]).index("by_author", ["authorId"]),
  issueVotes: defineTable({ issueId: v.id("issues"), userId: v.id("profiles"), createdAt: v.number() }).index("by_issue", ["issueId"]).index("by_user_issue", ["userId", "issueId"]),
  issueFollowers: defineTable({ issueId: v.id("issues"), userId: v.id("profiles"), createdAt: v.number() }).index("by_issue", ["issueId"]).index("by_user_issue", ["userId", "issueId"]),
  notifications: defineTable({ recipientId: v.id("profiles"), type: v.string(), issueId: v.optional(v.id("issues")), title: v.string(), message: v.string(), isRead: v.boolean(), createdAt: v.number() }).index("by_recipient", ["recipientId", "createdAt"]).index("by_recipient_unread", ["recipientId", "isRead"]),
})
