'use client'
import Link from 'next/link'
import { useState } from 'react'
import { useMutation,useQuery } from 'convex/react'
import { useConvexAuth } from '@convex-dev/auth/react'
import { api } from '@/convex/_generated/api'
import { ArrowLeft,Loader2,ShieldCheck } from 'lucide-react'
const label=(v:string)=>v.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())
export default function AdminPage(){
 const {isLoading,isAuthenticated}=useConvexAuth(),data=useQuery(api.issues.adminOverview,isAuthenticated?{}:'skip'),departments=useQuery(api.issues.departments,isAuthenticated?{}:'skip'),assignRole=useMutation(api.issues.assignRole)
 const [busy,setBusy]=useState<string>(''),[error,setError]=useState('')
 if(isLoading||(isAuthenticated&&!data))return <main className="grid min-h-screen place-items-center bg-[#f6f8fb]"><Loader2 className="animate-spin text-slate-400"/></main>
 if(!isAuthenticated)return <main className="grid min-h-screen place-items-center bg-[#f6f8fb] p-6 text-center"><div><h1 className="text-xl font-bold">Sign in required</h1><Link href="/" className="mt-5 inline-block text-sm font-semibold text-[#245582]">Go to dashboard</Link></div></main>
 if(!data)return null
 async function save(profileId:string,role:string,departmentId:string){setError('');setBusy(profileId);try{await assignRole({profileId:profileId as never,role:role as never,departmentId:departmentId?departmentId as never:undefined})}catch(e){setError(e instanceof Error?e.message:'Unable to update role.')}finally{setBusy('')}}
 return <main className="min-h-screen bg-[#f6f8fb] p-6 text-slate-900 sm:p-10"><div className="mx-auto max-w-6xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-medium text-[#245582]"><ArrowLeft size={16}/> Dashboard</Link><div className="mt-7 flex items-center gap-3"><ShieldCheck className="text-[#245582]"/><div><h1 className="text-3xl font-bold">Administration</h1><p className="text-sm text-slate-500">Manage operational roles and department access.</p></div></div>{error&&<p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="mt-7 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-400">Users</p><strong className="text-2xl">{data.users.length}</strong></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-400">Departments</p><strong className="text-2xl">{data.departments.length}</strong></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs text-slate-400">Categories</p><strong className="text-2xl">{data.categories.length}</strong></div></div><section className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-bold">Users and access</h2><p className="mt-1 text-xs text-slate-400">Role changes are protected by the super-admin server mutation.</p></div><div className="divide-y divide-slate-100">{data.users.map(user=><div key={user._id} className="grid gap-3 p-4 sm:grid-cols-[1fr_180px_180px_auto] sm:items-center"><div><strong className="text-sm">{user.name}</strong><p className="text-xs text-slate-400">{user.email}</p></div><select id={`role-${user._id}`} defaultValue={user.role} className="h-9 rounded-lg border border-slate-200 px-2 text-xs"><option value="citizen">Citizen</option><option value="department_staff">Department staff</option><option value="department_admin">Department admin</option><option value="super_admin">Super admin</option></select><select id={`dept-${user._id}`} defaultValue={user.departmentId??''} className="h-9 rounded-lg border border-slate-200 px-2 text-xs"><option value="">No department</option>{(departments??data.departments).map(d=><option key={d._id} value={d._id}>{d.name}</option>)}</select><button disabled={busy===user._id} onClick={()=>{const role=(document.getElementById(`role-${user._id}`) as HTMLSelectElement).value;const dept=(document.getElementById(`dept-${user._id}`) as HTMLSelectElement).value;void save(user._id,role,dept)}} className="rounded-lg bg-[#245582] px-3 py-2 text-xs font-semibold text-white disabled:opacity-40">{busy===user._id?'Saving…':'Save'}</button></div>)}</div></section></div></main>
}
