'use client'

import Link from 'next/link'
import { use, useState } from 'react'
import { useMutation, useQuery } from 'convex/react'
import { useConvexAuth } from '@convex-dev/auth/react'
import { api } from '@/convex/_generated/api'
import { ArrowLeft, CheckCircle2, Clock3, Loader2, MessageCircle, ShieldAlert, ThumbsUp, UserRoundPlus } from 'lucide-react'

const date=(value:number)=>new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short'}).format(value)
const label=(value:string)=>value.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())
const statuses=['UNDER_REVIEW','VERIFIED','ASSIGNED','IN_PROGRESS','RESOLVED','COMMUNITY_VERIFICATION','REJECTED','REOPENED'] as const

export default function IssueDetailPage({params}:{params:Promise<{id:string}>}){
 const {id}=use(params),{isAuthenticated}=useConvexAuth()
 const issue=useQuery(api.issues.byId,isAuthenticated?{issueId:id as never}:'skip')
 const comments=useQuery(api.issues.comments,isAuthenticated?{issueId:id as never}:'skip')
 const support=useQuery(api.issues.support,isAuthenticated?{issueId:id as never}:'skip')
 const following=useQuery(api.issues.following,isAuthenticated?{issueId:id as never}:'skip')
 const sla=useQuery(api.issues.slaStatus,isAuthenticated?{issueId:id as never}:'skip')
 const ai=useQuery(api.issues.aiAnalysis,isAuthenticated?{issueId:id as never}:'skip')
 const evidence=useQuery(api.issues.resolutionEvidence,isAuthenticated?{issueId:id as never}:'skip')
 const staff=useQuery(api.issues.departmentStaff,isAuthenticated?{}:'skip')
 const addComment=useMutation(api.issues.addComment),toggleSupport=useMutation(api.issues.toggleSupport),toggleFollowing=useMutation(api.issues.toggleFollowing)
 const transition=useMutation(api.issues.transition),assignIssue=useMutation(api.issues.assignIssue),generateUploadUrl=useMutation(api.issues.generateUploadUrl),addResolutionEvidence=useMutation(api.issues.addResolutionEvidence),verifyResolution=useMutation(api.issues.verifyResolution)
 const [comment,setComment]=useState(''),[error,setError]=useState(''),[verificationError,setVerificationError]=useState(''),[busy,setBusy]=useState(false),[assigneeId,setAssigneeId]=useState(''),[evidenceFile,setEvidenceFile]=useState<File|null>(null),[evidenceNote,setEvidenceNote]=useState('')
 if(!isAuthenticated)return <main className="grid min-h-screen place-items-center bg-[#f6f8fb] p-6"><div className="text-center"><h1 className="text-xl font-bold">Sign in required</h1><Link href="/" className="mt-5 inline-block text-sm font-semibold text-[#245582]">Go to sign in</Link></div></main>
 if(issue===undefined||comments===undefined||support===undefined||following===undefined||sla===undefined||ai===undefined||evidence===undefined)return <main className="grid min-h-screen place-items-center bg-[#f6f8fb] text-slate-500"><Loader2 className="animate-spin"/></main>
 if(!issue)return <main className="grid min-h-screen place-items-center bg-[#f6f8fb] p-6"><div className="text-center"><ShieldAlert className="mx-auto text-slate-300" size={40}/><h1 className="mt-3 text-xl font-bold">Issue unavailable</h1><Link href="/my-issues" className="mt-5 inline-block text-sm font-semibold text-[#245582]">Back to My Issues</Link></div></main>
 const operational=issue.canTransition
 async function act(fn:()=>Promise<unknown>){setError('');setBusy(true);try{await fn()}catch(e){setError(e instanceof Error?e.message:'Action failed.')}finally{setBusy(false)}}
 async function submitComment(){if(comment.trim().length<2)return;await act(async()=>{await addComment({issueId:issue._id,body:comment});setComment('')})}
 async function verify(accepted:boolean){await act(async()=>{try{await verifyResolution({issueId:issue!._id,accepted})}catch(e){setVerificationError(e instanceof Error?e.message:'Unable to update resolution.')}})}
 async function uploadResolutionEvidence(){if(!evidenceFile)return;await act(async()=>{const url=await generateUploadUrl();const res=await fetch(url,{method:'POST',headers:{'Content-Type':evidenceFile.type},body:evidenceFile});if(!res.ok)throw new Error('Evidence upload failed.');const {storageId}=await res.json();await addResolutionEvidence({issueId:issue._id,storageId,description:evidenceNote});setEvidenceFile(null);setEvidenceNote('')})}
 return <main className="min-h-screen bg-[#f6f8fb] px-5 py-8 text-slate-900 sm:px-8"><div className="mx-auto max-w-5xl"><Link href="/my-issues" className="inline-flex items-center gap-2 text-sm font-medium text-[#245582]"><ArrowLeft size={16}/> My issues</Link>
 <article className="mt-7 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><span className="rounded bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-500">{issue.referenceNumber}</span><h1 className="mt-3 text-2xl font-bold">{issue.title}</h1><p className="mt-2 text-sm leading-6 text-slate-600">{issue.description}</p></div><div className="sm:text-right"><p className="text-sm font-bold text-[#245582]">{label(issue.status)}</p><p className="mt-1 text-xs text-slate-400">{label(issue.priority)} priority · {issue.address}</p></div></div>
 <div className="mt-6 grid gap-3 border-t border-slate-100 pt-5 text-sm sm:grid-cols-4"><p><span className="text-slate-400">Category</span><br/><strong>{issue.categoryName}</strong></p><p><span className="text-slate-400">Department</span><br/><strong>{issue.departmentName}</strong></p><p><span className="text-slate-400">Assignee</span><br/><strong>{issue.assignee?.name??'Unassigned'}</strong></p><p><span className="text-slate-400">SLA</span><br/><strong className={sla.status==='OVERDUE'?'text-rose-600':''}>{label(sla.status)}</strong></p></div>
 {issue.isDuplicate&&<div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Possible duplicate report detected{issue.duplicateOf?' · linked to an earlier report.':''}</div>}
 {ai&&<section className="mt-5 rounded-xl border border-violet-200 bg-violet-50 p-4"><p className="text-sm font-bold text-violet-900">AI triage</p><p className="mt-1 text-xs text-violet-800">{ai.summary}</p><div className="mt-3 flex flex-wrap gap-2 text-[11px]"><span className="rounded-full bg-white px-2 py-1">Severity: {ai.severity}</span><span className="rounded-full bg-white px-2 py-1">Suggested category: {ai.suggestedCategory}</span><span className="rounded-full bg-white px-2 py-1">Department: {ai.suggestedDepartment}</span>{ai.safetyConcern&&<span className="rounded-full bg-rose-100 px-2 py-1 text-rose-700">Safety concern</span>}</div></section>}
 {operational&&<section className="mt-6 rounded-xl border border-slate-200 bg-slate-50 p-4"><h2 className="font-bold">Department operations</h2><div className="mt-3 flex flex-col gap-3 sm:flex-row"><select value={issue.assignee?.id??assigneeId} onChange={e=>setAssigneeId(e.target.value)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">Unassigned</option>{staff?.filter(s=>s.departmentId===issue.departmentId).map(s=><option key={s._id} value={s._id}>{s.name} · {label(s.role)}</option>)}</select><button disabled={busy||!assigneeId} onClick={()=>act(()=>assignIssue({issueId:issue._id,assigneeId:assigneeId as never}))} className="rounded-lg bg-[#245582] px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Assign</button><select value="" onChange={e=>{if(e.target.value)void act(()=>transition({issueId:issue._id,newStatus:e.target.value as never}))}} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">Change status…</option>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></div>
 <div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]"><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>setEvidenceFile(e.target.files?.[0]??null)} className="text-xs"/><button disabled={busy||!evidenceFile||evidenceNote.trim().length<3} onClick={uploadResolutionEvidence} className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Upload resolution proof</button></div><input value={evidenceNote} onChange={e=>setEvidenceNote(e.target.value)} placeholder="Describe the resolution evidence" maxLength={500} className="mt-2 h-10 w-full rounded-lg border border-slate-200 px-3 text-sm"/>
 </section>}
 {evidence.length>0&&<section className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><h2 className="flex items-center gap-2 font-bold text-emerald-900"><CheckCircle2 size={17}/> Resolution evidence</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{evidence.map(item=><a key={item._id} href={item.url??'#'} target="_blank" rel="noreferrer" className="rounded-lg border border-emerald-100 bg-white p-3 text-sm hover:border-emerald-300"><strong>{item.description}</strong><p className="mt-1 text-xs text-slate-400">{date(item.createdAt)}</p></a>)}</div></section>}
 {issue.status==='COMMUNITY_VERIFICATION'&&<section className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-sm font-semibold text-amber-900">Was this issue actually resolved?</p>{verificationError&&<p className="mt-2 text-xs text-rose-700">{verificationError}</p>}<div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>void verify(true)} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-semibold text-white">Yes, resolved</button><button onClick={()=>void verify(false)} className="rounded-lg border border-amber-300 px-3 py-2 text-xs font-semibold text-amber-900">No, reopen</button></div></section>}
 <div className="mt-6 flex flex-wrap gap-3 border-t border-slate-100 pt-5"><button onClick={()=>toggleSupport({issueId:issue._id})} className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold ${support.supported?'bg-[#245582] text-white':'border border-slate-200 text-slate-700'}`}><ThumbsUp size={16}/> {support.supported?'Supported':'Support'} · {support.count}</button><button onClick={()=>toggleFollowing({issueId:issue._id})} className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold ${following?'bg-slate-800 text-white':'border border-slate-200 text-slate-700'}`}><UserRoundPlus size={16}/> {following?'Following':'Follow issue'}</button></div>
 <section className="mt-8 border-t border-slate-100 pt-6"><h2 className="flex items-center gap-2 text-lg font-bold"><MessageCircle size={19} className="text-[#245582]"/> Community discussion <span className="text-sm font-normal text-slate-400">{comments.length}</span></h2><div className="mt-4 space-y-3">{comments.length===0?<p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-500">Be the first to add a helpful update.</p>:comments.map(item=><div key={item._id} className="rounded-lg border border-slate-100 p-4"><div className="flex justify-between gap-3"><strong className="text-sm">{item.authorName}</strong><time className="text-xs text-slate-400">{date(item.createdAt)}</time></div><p className="mt-2 text-sm leading-6 text-slate-600">{item.body}</p></div>)}</div><textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={1000} rows={3} placeholder="Share a helpful update" className="mt-5 w-full rounded-lg border border-slate-200 p-3 text-sm outline-none"/><div className="mt-2 flex justify-between"><span className="text-xs text-slate-400">{comment.length}/1000</span><button onClick={submitComment} disabled={busy||comment.trim().length<2} className="rounded-lg bg-[#245582] px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Post comment</button></div>{error&&<p role="alert" className="mt-2 text-sm text-rose-600">{error}</p>}</section>
 </article></div></main>
}
