'use client'

import Link from 'next/link'
import dynamic from 'next/dynamic'
import { useState } from 'react'
import { useQuery } from 'convex/react'
import { api } from '@/convex/_generated/api'
const PublicIssueMap = dynamic(() => import('@/components/public-issue-map').then((module) => module.PublicIssueMap), { ssr: false, loading: () => <div className="grid h-[min(70vh,560px)] min-h-80 place-items-center rounded-2xl bg-slate-50 text-sm text-slate-500">Loading map…</div> })

export default function PublicMapPage() { const [status, setStatus] = useState(''); const [category, setCategory] = useState(''); const issues = useQuery(api.issues.publicMap, { status: status || undefined, category: category || undefined }); const categories = Array.from(new Set((issues ?? []).map((issue) => issue.categoryName).filter(Boolean))) as string[]; return <main className="min-h-screen bg-[#f6f8fb] px-4 py-8 sm:px-8"><div className="mx-auto max-w-6xl"><Link href="/" className="text-sm font-semibold text-[#245582]">← Back to CivicFix</Link><div className="mt-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#2d8c88]">Community visibility</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-900">Public issue map</h1><p className="mt-2 max-w-xl text-sm text-slate-500">Explore public reports by location. Reporter identity and private details are never shown.</p></div><div className="flex flex-wrap gap-2"><select aria-label="Filter by status" value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"><option value="">All statuses</option><option value="SUBMITTED">Submitted</option><option value="IN_PROGRESS">In progress</option><option value="RESOLVED">Resolved</option></select><select aria-label="Filter by category" value={category} onChange={(event) => setCategory(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"><option value="">All categories</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</select></div></div>{issues === undefined ? <div className="mt-8 grid h-96 place-items-center rounded-2xl border border-slate-200 bg-white text-sm text-slate-500">Loading public reports…</div> : issues.length === 0 ? <div className="mt-8 grid h-96 place-items-center rounded-2xl border border-dashed border-slate-300 bg-white text-sm text-slate-500">No public reports match these filters.</div> : <div className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white p-2 shadow-sm"><PublicIssueMap issues={issues}/></div>}</div></main> }
