'use client'

import Link from 'next/link'
import { useState } from 'react'
import { useConvexAuth, useMutation, useQuery } from 'convex/react'
import { Loader2, ShieldCheck } from 'lucide-react'
import { api } from '@/convex/_generated/api'

export default function ModerationPage() { const { isLoading, isAuthenticated } = useConvexAuth(); const reports = useQuery(api.issues.moderationReports, isAuthenticated ? {} : 'skip'); const review = useMutation(api.issues.reviewModerationReport); const [error, setError] = useState(''); if (isLoading || (isAuthenticated && reports === undefined)) return <main className="grid min-h-screen place-items-center bg-[#f6f8fb]"><Loader2 className="animate-spin text-slate-400"/></main>; if (!isAuthenticated) return <main className="grid min-h-screen place-items-center bg-[#f6f8fb] p-6 text-center"><div><h1 className="text-xl font-bold text-slate-900">Sign in required</h1><p className="mt-2 text-sm text-slate-500">Moderation is limited to authorized staff.</p><Link href="/" className="mt-5 inline-block text-sm font-semibold text-[#245582]">Go to dashboard</Link></div></main>; return <main className="min-h-screen bg-[#f6f8fb] px-4 py-8 sm:px-8"><div className="mx-auto max-w-5xl"><Link href="/" className="text-sm font-semibold text-[#245582]">← Back to CivicFix</Link><div className="mt-8 flex items-center gap-3"><ShieldCheck className="text-[#245582]"/><div><h1 className="text-3xl font-bold text-slate-900">Moderation review</h1><p className="mt-1 text-sm text-slate-500">Review abuse reports without exposing reporter identity.</p></div></div>{error && <p role="alert" className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{reports?.length === 0 ? <div className="mt-8 rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No open reports.</div> : <div className="mt-8 space-y-3">{reports?.map((report) => <article key={report._id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{report.issue?.referenceNumber ?? 'General report'}</p><h2 className="mt-1 font-semibold text-slate-900">{report.issue?.title ?? 'Report without linked issue'}</h2><p className="mt-2 text-sm text-slate-600">{report.reason}</p></div><div className="flex shrink-0 flex-wrap gap-2"><button onClick={async () => { try { await review({ reportId: report._id, action: 'DISMISS' }) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to review report.') } }} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold">Dismiss</button><button onClick={async () => { try { await review({ reportId: report._id, action: 'HIDE_ISSUE' }) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to hide issue.') } }} className="rounded-lg bg-rose-700 px-3 py-2 text-xs font-semibold text-white">Hide issue</button></div></div></article>)}</div>}</div></main> }
